server:
  port: 9503

spring:
  application:
    name: auth-service

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: cSCkuYKnF6IjUa5FtldYC3ByXELil1ziq4FcSbnKrgsQm6ae47dpnNvHWXYaYUU
  validity: 20

  spring:
    main:
      web-application-type: reactive