server:
  port: 9500

spring:
  profiles:
    active: path
  application:
    name: api-gateway
  jackson:
    default-property-inclusion: NON_NULL

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: secretkey
