spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9501
          predicates:
            - Path= /user/**
          filters:
            - StripPrefix=1
        - id: todo-service
          uri: http://localhost:9502
          predicates:
            - Path= /todo/**
          filters:
            - StripPrefix=1