spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9501
          predicates:
            - Path= /user/*
          filters:
            - StripPrefix=1 # required to strip the prefix made to the request . Ex /jio/customers request will go to jio service as /customers
        - id: to-do-service
          uri: http://localhost:9502
          predicates:
            - Path= /todo/*
          filters:
            - StripPrefix=1