server:
  port: 9502

spring:
  application:
    name: todo-service
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka