server:
  port: 9501

spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./user-service-db
  jackson:
    default-property-inclusion: NON_NULL

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#secret key - should be encrypted
  jwt:
    secret: secretkey
  #3 minutes validity
    token:
      validity: 180000